# Generated by Django 4.2 on 2023-05-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_alter_property_options_propertyvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='property_values',
            field=models.ManyToManyField(to='stories.propertyvalue'),
        ),
    ]
