# Generated by Django 4.2 on 2023-06-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_alter_comment_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='property_values',
        ),
    ]
