# Generated by Django 4.2 on 2023-07-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='email'),
        ),
    ]
